name: CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Auth
      uses: google-github-actions/auth@v2
      with:
        project_id: goi-machine
        workload_identity_provider: projects/352431468635/locations/global/workloadIdentityPools/github/providers/my-repo
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - name: 'Use gcloud CLI'
      run: 'gcloud app describe'
    - name: Deploy
      run: sbt -v deploy
